### ISSUE TITLE
Number of weeks incorrect

### ISSUE THREAD

**Issue by mikemand** [carvefx/calendar#3]
Hello,

Instead of using `Calendar::WEEKS_IN_MONTH`, the Calendar is only creating 5 weeks for July 2016:

![screen shot 2016-08-11 at 3 59 12 pm](https://cloud.githubusercontent.com/assets/745184/17606445/cbe24b1e-5fdc-11e6-8769-3e6950e830d6.png)

I am invoking it like so:

```php
$year = 2016; // Set by URL parameter
$month = 7; // Set by URL parameter
$now = Carbon::create($year, $month);
$calendar = new Calendar($now->year, $now->month);
```

And displaying as such:

```blade
<table>
    <thead>
        <tr>
        @foreach($calendar->getWeeks()[0]->getDays() as $days)
            <th>{{ $days->format('l') }}</th>
        @endforeach
        </tr>
    </thead>
    <tbody>
        @foreach($calendar->getWeeks() as $week)
            <tr>
            @foreach($week->getDays() as $day)
                <td>
                    <div class="day">{{ $day->isBlankDay() ? null : $day->day }}</div>
                </td>
            @endforeach
            </tr>
        @endforeach
    </tbody>
</table>
```

Also, is there any way to guarantee which day of the week the Calendar will start on, every month?

**Comment by mikemand** [comment]
Fixed in my fork. https://github.com/kmdwebdesigns/calendar

**Comment by carvefx** [comment]
Hi Micheal - sorry for the slow reply, I've been (and still am) on holiday these past days. Would it be too much to ask to submit a pull request with your changes so that I can include them in the main package?

Thanks
Adrian

**Comment by mikemand** [comment]
Hi Adrian,

Sure! I didn't check activity before opening my issue, so once I saw that the last commit was 2 years ago, I thought it might be abandoned. I will open a PR with the fixes as soon as I can.

Thank you!

**Comment by florentsorel** [comment]
I think the problem still exists. See my issue here https://github.com/carvefx/calendar/issues/6
