### ISSUE TITLE
Start at Monday

### ISSUE THREAD

**Issue by florentsorel** [carvefx/calendar#5]
Hello,

It's possible to display the calendar and start to Monday?

```php
new Calendar(2017, 4) // start a sunday, screen above
new Calendar(2017,5); // start a monday, everything is ok here
```

I would like to have the same thing for any date.

![image](https://cloud.githubusercontent.com/assets/1011503/24913209/bba48f2e-1ed0-11e7-8ded-a5248931af6a.png)

**Comment by mikemand** [comment]
Hi @florentsorel,

From my experience, you can use Carbon's `setWeekStartsAt` and `setWeekEndsAt` methods (before creating the calendar object) to change the start/end day of the week:

```php
Carbon::setWeekStartsAt(Carbon::MONDAY);
Carbon::setWeekEndsAt(Carbon::SUNDAY);
```

**Comment by florentsorel** [comment]
It's not working :/ I updated the package version to dev-master but now all month start a sunday.

**Comment by mikemand** [comment]
Hi @florentsorel,

I think that might be my fault. I was trying to fix the calendar being variable on the day of the week that each month started on (some would start on Monday, some would start on Sunday, depending on the first day of the month) so forced it to use Sunday as the start of the week.

On my fork, I have fixed this. I have also added Timezone support.

In your `composer.json` add the following above the `require` block:

```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/kmdwebdesigns/calendar"
    }
],
```

Then you can use `^1.0` as your version constraint: `"carvefx/calendar": "^1.0"`.

**Comment by florentsorel** [comment]
I can't install the `^1.0` version, I have the following errors:

```
- Installation request for nesbot/carbon (locked at 1.21.0, required as ^1.21) -> satisfiable by nesbot/carbon[1.21.0].
- Conclusion: don't install nesbot/carbon 1.22.1
- carvefx/calendar v1.0.1 requires nesbot/carbon ^1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1].
- carvefx/calendar v1.0.0 requires nesbot/carbon ^1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1].
- Conclusion: don't install nesbot/carbon 1.22.0
- Installation request for carvefx/calendar ^1.0 -> satisfiable by carvefx/calendar[v1.0.1, v1.0.0].
```

**Comment by mikemand** [comment]
Hi @florentsorel,

I've tagged `v1.0.2` which relaxes the Carbon version requirement a little bit (it is now `^1.20` instead of `^1.22`). Let me know if that works.

**Comment by florentsorel** [comment]
Yes it's works ;) but still not working for the fix https://github.com/kmdwebdesigns/calendar/commit/a0dbcdb491998481afc9947a3256b19f4dd2a903#diff-96039760a7d45c970cc84b98f819f5f6R42
